CREATE TYPE FORM_OF_EDUCATION AS ENUM (
    'DISTANCE_EDUCATION',
    'FULL_TIME_EDUCATION',
    'EVENING_CLASSES'
);
CREATE TYPE COLOR AS ENUM (
    'RED',
    'ORANGE',
    'WHITE',
    'YELLOW'
);
CREATE TYPE COUNTRY AS ENUM (
    'FRANCE',
    'INDIA',
    'VATICAN',
    'THAILAND',
    'JAPAN'
);
CREATE TYPE SEMESTER AS ENUM (
    'SECOND',
    'THIRD',
    'FIFTH',
    'SEVENTH',
    'EIGHTH'
);